package com.idega.block.cal.business;

import java.io.IOException;
import java.rmi.RemoteException;
import java.sql.Timestamp;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.servlet.ServletException;
import com.idega.block.cal.data.CalendarEntry;
import com.idega.block.rss.business.RSSAbstractProducer;
import com.idega.block.rss.business.RSSBusiness;
import com.idega.block.rss.business.RSSProducer;
import com.idega.block.rss.data.RSSRequest;
import com.idega.business.IBOLookup;
import com.idega.business.IBOLookupException;
import com.idega.presentation.IWContext;
import com.idega.slide.business.IWContentEvent;
import com.idega.slide.business.IWSlideChangeListener;
import com.idega.slide.business.IWSlideService;
import com.sun.syndication.feed.synd.SyndContent;
import com.sun.syndication.feed.synd.SyndContentImpl;
import com.sun.syndication.feed.synd.SyndEntry;
import com.sun.syndication.feed.synd.SyndEntryImpl;
import com.sun.syndication.feed.synd.SyndFeed;

/**
 * 
 * @author justinas
 *
 */

public class CalendarRSSProducer  extends RSSAbstractProducer implements RSSProducer, IWSlideChangeListener{
	private List rssFileURIsCacheList = new ArrayList();
	private static final int DATE_LENGTH = 8;
	
	public void handleRSSRequest(RSSRequest rssRequest) throws IOException {
		String extraURI = rssRequest.getExtraUri();
		String feedParentFolder = null;
		String feedFile = null;
		if(extraURI == null)
			extraURI = "";
		if((!extraURI.endsWith("/")) && (extraURI.length() != 0))
			extraURI = extraURI.concat("/");
		
		IWContext iwc = getIWContext(rssRequest);
		String uri = null;
		if(extraURI.startsWith("period")){
			try {
				feedParentFolder = "/files/cms/calendar/rss/period/";
				uri = extraURI.substring("period/".length(), extraURI.length());
				feedFile = "period_"+getName(uri)+iwc.getLocale().getLanguage()+".xml";
			} catch (RuntimeException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		else if(extraURI.startsWith("group")){
			feedParentFolder = "/files/cms/calendar/rss/group/";
			uri = extraURI.substring("group/".length(), extraURI.length());
			feedFile = "group_"+getName(uri)+getPeriod(uri)+iwc.getLocale().getLanguage()+".xml";
		}
		else if(extraURI.startsWith("ledger")){
			feedParentFolder = "/files/cms/calendar/rss/ledger/";
			feedFile = "ledger_"+extraURI.substring("ledger/".length(), extraURI.length()-1)+"_"+iwc.getLocale().getLanguage()+".xml";			
		}
		else if(extraURI.startsWith("events")){
			feedParentFolder = "/files/cms/calendar/rss/events/";
			uri = extraURI.substring("events/".length(), extraURI.length());
			feedFile = "events_"+getTypesString(uri)+getPeriod(uri)+iwc.getLocale().getLanguage()+".xml";
		}
		else{
//			TODO handle wrong URI
		}
		String realURI = "/content"+feedParentFolder+feedFile;	
		
		if(rssFileURIsCacheList.contains(feedFile)){
//		if(false){
			try {
				this.dispatch(realURI, rssRequest);
			} catch (ServletException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		else{
			//generate rss and store and the dispatch to it
			//and add a listener to that directory
			try {
				searchForEntries(rssRequest,feedParentFolder,feedFile, extraURI);
				rssFileURIsCacheList.add(feedFile);
					
				this.dispatch(realURI, rssRequest);
			} catch (Exception e) {
				throw new IOException(e.getMessage());
			}
		}
	}
	
	public void searchForEntries(RSSRequest rssRequest, String feedParentFolder, String feedFileName, String extraURI) {
		IWContext iwc = getIWContext(rssRequest);
		Collection entries = null;
		if(extraURI.startsWith("period"))
			entries = getEntriesByPeriod(extraURI);
		if(extraURI.startsWith("group"))
			entries = getEntriesByGroup(extraURI);
		if(extraURI.startsWith("ledger"))
			entries = getEntriesByLedger(extraURI);
		if(extraURI.startsWith("events"))
			entries = getEntriesByEvents(extraURI);		
		if (entries != null){
			Date now = new Date();
			RSSBusiness rss = null;
			try {
				rss = (RSSBusiness) IBOLookup.getServiceInstance(iwc,RSSBusiness.class);			
			} catch (IBOLookupException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			String serverName = iwc.getServerURL();
			serverName = serverName.substring(0, serverName.length()-1);
			SyndFeed allArticles = null;
			if (entries.isEmpty()){
				allArticles = rss.createNewFeed("No entries found", serverName , "Calendar feed generated by IdegaWeb ePlatform, Idega Software, http://www.idega.com", "atom_1.0", iwc.getCurrentLocale().toString(), new Timestamp(now.getTime()));
				feedParentFolder = "/files/cms/calendar/rss/";
				feedFileName = "empty_"+iwc.getLocale().getLanguage()+".xml";		
			}
			else
				allArticles = rss.createNewFeed("title", serverName , "Calendar feed generated by IdegaWeb ePlatform, Idega Software, http://www.idega.com", "atom_1.0", iwc.getCurrentLocale().toString(), new Timestamp(now.getTime()));
			
			List syndEntries = new ArrayList();
			try {
				List calendarEntries = new ArrayList(entries);
				CalendarEntry calEntry = null;
				for (int i = 0; i < entries.size(); i++) {
					SyndEntry sEntry = new SyndEntryImpl();
					calEntry = (CalendarEntry)calendarEntries.get(i);
					SyndContent scont = new SyndContentImpl();
					String content = "Name: "+calEntry.getName()+" Type: "+calEntry.getEntryTypeName()+" From: "+calEntry.getDate()+" To: "+calEntry.getEndDate();					
					scont.setValue(content);
					sEntry.setTitle(calEntry.getName());
					sEntry.setDescription(scont);
					sEntry.setPublishedDate(calEntry.getDate());
					syndEntries.add(sEntry);
				}
			} catch (RuntimeException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
			allArticles.setEntries(syndEntries);
			try {
				String allArticlesContent = rss.convertFeedToAtomXMLString(allArticles);
				IWSlideService service = this.getIWSlideService(rssRequest);
				service.uploadFileAndCreateFoldersFromStringAsRoot(feedParentFolder, feedFileName, allArticlesContent, this.RSS_CONTENT_TYPE, true);
			} catch (RemoteException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (Exception e) {
				e.printStackTrace();
			}			
		}
	}	
	
	public void onSlideChange(IWContentEvent contentEvent) {
//		On a file change this code checks if an rss file already exists and if so updates it (overwrites) with a new folder list
		String URI = contentEvent.getContentEvent().getUri();
		//only do it for articles (whenever something changes in the articles folder)
		if(URI.indexOf("/cms/calendar/")>-1){
			//TODO dont remove cache on COmments change, just check the URI for commentesrss.
			getrssFileURIsCacheList().clear();
		}
	}
	protected List getrssFileURIsCacheList() {
		return rssFileURIsCacheList;
	}
	private Collection getEntriesByPeriod(String extraURI){
		String period = extraURI.substring("period/".length());
		String fromStr = period.substring(0, DATE_LENGTH);
		String toStr = period.substring(DATE_LENGTH+1, period.length()-1);
		Timestamp fromTmst = getTimeStampFromString(fromStr);
		Timestamp toTmst = getTimeStampFromString(toStr);
		CalBusiness calendar = new CalBusinessBean(); 
		return calendar.getEntriesBetweenTimestamps(fromTmst, toTmst);
	}
	
	private Collection getEntriesByGroup(String extraURI){
		String group = extraURI.substring("group/".length());
		String groupID = group.substring(0, group.indexOf("/"));
		String groupPeriod = group.substring(groupID.length()+1, group.length());
		Timestamp from = null;
		Timestamp to = null;
		CalBusiness calendar = new CalBusinessBean();
		int entryGroupID;
		try {
			entryGroupID = Integer.parseInt(groupID);
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return null;
		}		
		if (groupPeriod.length() != 0){
			String fromStr = groupPeriod.substring(0, DATE_LENGTH);
			String toStr = groupPeriod.substring(DATE_LENGTH+1, groupPeriod.length()-1);
			from = getTimeStampFromString(fromStr);
			to = getTimeStampFromString(toStr);
			Collection coll = calendar.getEntriesBetweenTimestamps(from, to);
			List entries = new ArrayList();
			for (Iterator iter = coll.iterator(); iter.hasNext();) {
				CalendarEntry element = (CalendarEntry) iter.next();
				int id = element.getGroupID();
				if (element.getGroupID() == entryGroupID){
					entries.add(element);
				}				
			}
			return entries;
		}		
		return calendar.getEntriesByICGroup(entryGroupID);
	}	
	
	private Collection getEntriesByLedger(String extraURI){
		String ledger = extraURI.substring("ledger/".length());
		String ledgerID = ledger.substring(0, ledger.indexOf("/"));
		String ledgerPeriod = ledger.substring(ledgerID.length()+1, ledger.length());		
		Timestamp from = null;
		Timestamp to = null;
		CalBusiness calendar = new CalBusinessBean();
		int ledgerIdInt;
		try {
			ledgerIdInt = Integer.parseInt(ledgerID);
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return null;
		}		
		if (ledgerPeriod.length() != 0){
			String fromStr = ledgerPeriod.substring(0, DATE_LENGTH);
			String toStr = ledgerPeriod.substring(DATE_LENGTH+1, ledgerPeriod.length()-1);
			from = getTimeStampFromString(fromStr);
			to = getTimeStampFromString(toStr);
			Collection coll = calendar.getEntriesBetweenTimestamps(from, to);
			List entries = new ArrayList();
			for (Iterator iter = coll.iterator(); iter.hasNext();) {
				CalendarEntry element = (CalendarEntry) iter.next();
				if (element.getLedgerID() == ledgerIdInt){
					entries.add(element);
				}				
			}
			return entries;
		}
		return calendar.getEntriesByLedgerID(ledgerIdInt);
	}	
	private Collection getEntriesByEvents(String extraURI){
		String events = extraURI.substring("events/".length());
		String eventsPeriod = null;
		List eventsList = new ArrayList();
		int index = -1;
		if (events.indexOf("+") == -1){
			eventsList.add(events.substring(0, events.indexOf("/")));
			events = events.substring(events.indexOf("/")+1, events.length());
		}
		else{
			while(true){
				index = events.indexOf("+");
				if (index == -1){
					index = events.indexOf("/");
					eventsList.add(events.substring(0, index));
					events = events.substring(index+1, events.length());
					break;
				}
				else{
					eventsList.add(events.substring(0, index));
					events = events.substring(index+1, events.length());
				}
			}
		}
		
		eventsPeriod = events;		
		Timestamp from = null;
		Timestamp to = null;
		CalBusiness calendar = new CalBusinessBean();
		
		if (eventsPeriod.length() != 0){
			String fromStr = eventsPeriod.substring(0, DATE_LENGTH);
			String toStr = eventsPeriod.substring(DATE_LENGTH+1, eventsPeriod.length()-1);
			from = getTimeStampFromString(fromStr);
			to = getTimeStampFromString(toStr);
			Collection coll = calendar.getEntriesBetweenTimestamps(from, to);
			List entries = new ArrayList();
			
			for (Iterator iter = coll.iterator(); iter.hasNext();) {
				CalendarEntry element = (CalendarEntry) iter.next();				
				if(eventsList.contains(element.getEntryTypeName())){	
					entries.add(element);
				}				
			}
			return entries;
		}
		Collection result = calendar.getEntriesByEvents(eventsList);
		return calendar.getEntriesByEvents(eventsList);
	}		
	private Timestamp getTimeStampFromString(String dateString){
		try {
			SimpleDateFormat simpleDate = new SimpleDateFormat("yyyyMMdd");
			Date date = simpleDate.parse(dateString, new ParsePosition(0));
			return new Timestamp(date.getTime());
		} catch (NumberFormatException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;		
	}
	
	private String getPeriod(String uri){
		if(uri.length() == 0)
			return "";
		String period = uri.substring(uri.indexOf("/")+1);		
		if(period.length() == 0)
			return "";
		if(period.startsWith("/"))
			return period.substring(1, period.length()-1)+"_";
		else return period.substring(0, period.length()-1)+"_";
	}

	private String getName(String extraURI){
		return extraURI.substring(0,extraURI.indexOf("/"))+"_";
	}
	
	private String getTypesString (String extraURI){
		String events = new String();
		try {
			List eventsList = getTypesList(extraURI);
			for (int i = 0; i < eventsList.size(); i++) {
				events = events.concat(eventsList.get(i)+"_");
			}
		} catch (RuntimeException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}		
		return events;		
	}
	
	private List getTypesList (String events){
		List eventsList = new ArrayList();
		
		int index;
		if (events.indexOf("+") == -1){
			eventsList.add(events.substring(0, events.indexOf("/")));
			events = events.substring(events.indexOf("/")+1, events.length());
		}
		else{
			while(true){
				index = events.indexOf("+");
				if (index == -1){
					index = events.indexOf("/");
					eventsList.add(events.substring(0, index));
					events = events.substring(index+1, events.length());
					break;
				}
				else{
					eventsList.add(events.substring(0, index));
					events = events.substring(index+1, events.length());
				}
			}
		}		
		return eventsList;		
	}
	
}
